### PR TITLE
Update redirects base for subdomain consolidation

### PR DESCRIPTION
**Pull request by schmalliso**

### CODE REVIEW

**Comment by schmalliso** [comment]
@terakilobyte Good to go for you!

**Comment by biniona-mongodb** [comment]
Hi @schmalliso, just for context I recently merged in #216. I definitely could be incorrect, but it looks like this PR (#217) may make similar updates. Should #217 be closed, or is this adding something not addressed by #216?

**Review by terakilobyte — APPROVED** [review]

**Comment by schmalliso** [comment]
This is in fact adding something #216 didn't address in that it moves the `docs/` to the prefix which ensures that the redirect created by the `raw: blabla` row actually ends up in the right folder in S3. Thanks @biniona-mongodb for your updates, though, they're :chefskiss:!

**Comment by schmalliso** [comment]
@terakilobyte I've convinced github that the 17 attempts made at merge conflict resolution were indeed things that happened and now we're happy here.

**Review by terakilobyte — APPROVED** [review]

**Pull request merged**
